# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Ghada\4thYear\GradProject\application\enemiesList (1).ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1267, 799)
        self.level_name = QtWidgets.QLabel(Dialog)
        self.level_name.setGeometry(QtCore.QRect(-10, 0, 1281, 102))
        self.level_name.setStyleSheet("background: rgb(0, 195, 122);\n"
"border-radius: 10px 10px 20px 20px;\n"
"opacity: 1;")
        self.level_name.setObjectName("level_name")
        self.sound_q = QtWidgets.QPushButton(Dialog)
        self.sound_q.setGeometry(QtCore.QRect(910, 190, 231, 111))
        self.sound_q.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_q.setObjectName("sound_q")
        self.sound_glottal = QtWidgets.QPushButton(Dialog)
        self.sound_glottal.setGeometry(QtCore.QRect(760, 310, 381, 111))
        self.sound_glottal.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_glottal.setObjectName("sound_glottal")
        self.sound_h = QtWidgets.QPushButton(Dialog)
        self.sound_h.setGeometry(QtCore.QRect(120, 430, 281, 111))
        self.sound_h.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_h.setObjectName("sound_h")
        self.sound_H = QtWidgets.QPushButton(Dialog)
        self.sound_H.setGeometry(QtCore.QRect(300, 310, 241, 111))
        self.sound_H.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_H.setObjectName("sound_H")
        self.sound_3 = QtWidgets.QPushButton(Dialog)
        self.sound_3.setGeometry(QtCore.QRect(820, 550, 311, 111))
        self.sound_3.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_3.setObjectName("sound_3")
        self.sound_8in = QtWidgets.QPushButton(Dialog)
        self.sound_8in.setGeometry(QtCore.QRect(720, 190, 171, 111))
        self.sound_8in.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_8in.setObjectName("sound_8in")
        self.sound_g = QtWidgets.QPushButton(Dialog)
        self.sound_g.setGeometry(QtCore.QRect(120, 190, 371, 111))
        self.sound_g.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_g.setObjectName("sound_g")
        self.sound_T = QtWidgets.QPushButton(Dialog)
        self.sound_T.setGeometry(QtCore.QRect(120, 310, 161, 111))
        self.sound_T.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_T.setObjectName("sound_T")
        self.sound_D = QtWidgets.QPushButton(Dialog)
        self.sound_D.setGeometry(QtCore.QRect(600, 550, 201, 111))
        self.sound_D.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_D.setObjectName("sound_D")
        self.sound_Z = QtWidgets.QPushButton(Dialog)
        self.sound_Z.setGeometry(QtCore.QRect(420, 430, 231, 111))
        self.sound_Z.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_Z.setObjectName("sound_Z")
        self.sound_S = QtWidgets.QPushButton(Dialog)
        self.sound_S.setGeometry(QtCore.QRect(510, 190, 191, 111))
        self.sound_S.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_S.setObjectName("sound_S")
        self.sound_r = QtWidgets.QPushButton(Dialog)
        self.sound_r.setGeometry(QtCore.QRect(560, 310, 181, 111))
        self.sound_r.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_r.setObjectName("sound_r")
        self.sound_j = QtWidgets.QPushButton(Dialog)
        self.sound_j.setGeometry(QtCore.QRect(670, 430, 291, 111))
        self.sound_j.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_j.setObjectName("sound_j")
        self.soundImage1_12 = QtWidgets.QLabel(Dialog)
        self.soundImage1_12.setGeometry(QtCore.QRect(40, 170, 1181, 531))
        self.soundImage1_12.setStyleSheet("\n"
"background: rgb(0, 195, 122);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.soundImage1_12.setObjectName("soundImage1_12")
        self.sound_w = QtWidgets.QPushButton(Dialog)
        self.sound_w.setGeometry(QtCore.QRect(980, 430, 161, 111))
        self.sound_w.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_w.setObjectName("sound_w")
        self.soundImage1_12.raise_()
        self.sound_w.raise_()
        self.sound_j.raise_()
        self.sound_r.raise_()
        self.sound_Z.raise_()
        self.sound_S.raise_()
        self.sound_glottal.raise_()
        self.sound_q.raise_()
        self.level_name.raise_()
        self.sound_h.raise_()
        self.sound_H.raise_()
        self.sound_3.raise_()
        self.sound_8in.raise_()
        self.sound_g.raise_()
        self.sound_T.raise_()
        self.sound_D.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.level_name.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; color:#ffffff;\">Enemies Level</span></p></body></html>"))
        self.sound_q.setText(_translate("Dialog", "/q/=ق"))
        self.sound_glottal.setText(_translate("Dialog", "/ʔ/=ء"))
        self.sound_h.setText(_translate("Dialog", "/h/=هـ"))
        self.sound_H.setText(_translate("Dialog", "/ħ/=ح"))
        self.sound_3.setText(_translate("Dialog", "/ʕ/=ع"))
        self.sound_8in.setText(_translate("Dialog", "/ɣ/=غ"))
        self.sound_g.setText(_translate("Dialog", "/g/=ج"))
        self.sound_T.setText(_translate("Dialog", "/ṭ/=ط"))
        self.sound_D.setText(_translate("Dialog", "/ḍ/=ض"))
        self.sound_Z.setText(_translate("Dialog", "/Z/=ظ"))
        self.sound_S.setText(_translate("Dialog", "/S/=ص"))
        self.sound_r.setText(_translate("Dialog", "/r/=ر"))
        self.sound_j.setText(_translate("Dialog", "/j/=س"))
        self.soundImage1_12.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:28pt; color:#ffffff;\">Choose a sound </span><span style=\" font-size:28pt; color:#00c37a;\">hhhhhhhhhhhhhhhhhhhhhhhhhh</span></p><p align=\"center\"><br/></p></body></html>"))
        self.sound_w.setText(_translate("Dialog", "/w/=و"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())