# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Ghada\4thYear\GradProject\application\Familylist (1).ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_family (object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 800)
        self.sound_m = QtWidgets.QPushButton(Dialog)
        self.sound_m.setGeometry(QtCore.QRect(790, 210, 261, 121))
        self.sound_m.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_m.setObjectName("sound_m")
        self.level_name = QtWidgets.QLabel(Dialog)
        self.level_name.setGeometry(QtCore.QRect(-5, 0, 1291, 102))
        self.level_name.setStyleSheet("background-color: rgb(66, 33, 255);\n"
"border-radius: 10px 10px 20px 20px;\n"
"opacity: 1;")
        self.level_name.setObjectName("level_name")
        self.sound_k = QtWidgets.QPushButton(Dialog)
        self.sound_k.setGeometry(QtCore.QRect(510, 350, 141, 121))
        self.sound_k.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_k.setObjectName("sound_k")
        self.sound_n = QtWidgets.QPushButton(Dialog)
        self.sound_n.setGeometry(QtCore.QRect(670, 350, 381, 121))
        self.sound_n.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_n.setObjectName("sound_n")
        self.sound_t = QtWidgets.QPushButton(Dialog)
        self.sound_t.setGeometry(QtCore.QRect(460, 490, 401, 121))
        self.sound_t.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_t.setObjectName("sound_t")
        self.sound_f = QtWidgets.QPushButton(Dialog)
        self.sound_f.setGeometry(QtCore.QRect(880, 490, 171, 121))
        self.sound_f.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_f.setObjectName("sound_f")
        self.sound_x = QtWidgets.QPushButton(Dialog)
        self.sound_x.setGeometry(QtCore.QRect(200, 350, 291, 121))
        self.sound_x.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_x.setObjectName("sound_x")
        self.soundImage1_16 = QtWidgets.QLabel(Dialog)
        self.soundImage1_16.setGeometry(QtCore.QRect(110, 180, 1031, 531))
        self.soundImage1_16.setStyleSheet("\n"
"background-color: rgb(66, 33, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.soundImage1_16.setObjectName("soundImage1_16")
        self.sound_l = QtWidgets.QPushButton(Dialog)
        self.sound_l.setGeometry(QtCore.QRect(200, 210, 571, 121))
        self.sound_l.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px 25px 35px 35px;\n"
"opacity: 1;")
        self.sound_l.setObjectName("sound_l")
        self.soundImage1_16.raise_()
        self.sound_x.raise_()
        self.sound_t.raise_()
        self.sound_f.raise_()
        self.sound_n.raise_()
        self.sound_k.raise_()
        self.sound_m.raise_()
        self.level_name.raise_()
        self.sound_l.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sound_m.setText(_translate("Dialog", "/m/=م"))
        self.level_name.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; color:#ffffff;\">Family Level</span></p></body></html>"))
        self.sound_k.setText(_translate("Dialog", "/k/=ك"))
        self.sound_n.setText(_translate("Dialog", "/n/=ن"))
        self.sound_t.setText(_translate("Dialog", "/t/=ت"))
        self.sound_f.setText(_translate("Dialog", "/f/=ف"))
        self.sound_x.setText(_translate("Dialog", "/x/=خ"))
        self.soundImage1_16.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:36pt; color:#ffffff;\">Choose a sound</span></p></body></html>"))
        self.sound_l.setText(_translate("Dialog", "/l/=ل"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_MainWindow_family ()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
